name: Automated Tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - test_home_page
          - test_days_page
          - test_book_1_page
          - test_grammar_page
          - test_book_2_page
          - test_learn_page
          - test_video_page
          - test_dropdown_menu_home_page
          - test_dropdown_days_page
          - test_search
          - whereis_test_search
          - pwd
          - ls_la


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: test_home_page
        if: "github.event.inputs.deployment_target == 'test_home_page'"
        run: pytest test_home_page.py

      - name: test_days_page
        if: "github.event.inputs.deployment_target == 'test_days_page'"
        run: pytest test_days_page.py

      - name: test_book_1_page
        if: "github.event.inputs.deployment_target == 'test_book_1_page'"
        run: pytest test_book_1_page.py

      - name: test_grammar_page
        if: "github.event.inputs.deployment_target == 'test_grammar_page'"
        run: pytest test_grammar_page.py

      - name: test_test_book_2_page
        if: "github.event.inputs.deployment_target == 'test_book_2_page'"
        run: pytest test_book_2_page.py

      - name: test_learn_page
        if: "github.event.inputs.deployment_target == 'test_learn_page'"
        run: pytest test_learn_page.py

      - name: test_video_page
        if: "github.event.inputs.deployment_target == 'test_video_page'"
        run: pytest test_video_page.py

      - name: test_video_page
        if: "github.event.inputs.deployment_target == 'test_video_page'"
        run: pytest test_video_page.py

      - name: test_dropdown_menu_home_page
        if: "github.event.inputs.deployment_target == 'test_dropdown_menu_home_page'"
        run: pytest test_dropdown_home_page.py

      - name: test_dropdown_days_page
        if: "github.event.inputs.deployment_target == 'test_dropdown_days_page'"
        run: pytest test_dropdown_days_page.py

      - name: where is test_search
        if: "github.event.inputs.deployment_target == 'whereis_test_search'"
        run: whereis test_search.py

      - name: pwd
        if: "github.event.inputs.deployment_target == 'pwd'"
        run: pwd

      - name: ls_la
        if: "github.event.inputs.deployment_target == 'ls_la'"
        run: ls -la

      - name: test_search
        if: "github.event.inputs.deployment_target == 'test_search'"
        run: pytest tests/test_search.py